use sales_data;
select * from products;
select * from customers; 
select * from orders;

    --   Advanced SQL Questions --  
	-- JOINS --
 -- Q1. Display customer name, product name, quantity, and order date for every order.
select
    customername,productname,quantity,orderdate
from customers
inner join orders
    on customers.customerid = orders.customerid;
    
-- Q2. Find the total quantity order by each customer.
select customername,
sum(quantity ) as total_amount_spent
from customers
inner join orders
on customers.customerid = orders.customerid
group by customername;

-- Q3. Display the top 5 customers based on total spending.
select customername,
sum(quantity * unitprice) as total_spending
from customers
inner join orders
on customers.customerid = orders.customerid
group by customername
order by total_spending desc
limit 5;

-- Q4. Find customers who have never placed an order.
select customername
from customers
left join orders
on customers.customerid = orders.customerid
where orders.customerid is null;

-- Q5. Display all customers along with their total number of orders.
select customername,
count(orders.orderid) as total_orders
from customers
left join orders
on customers.customerid = orders.customerid
group by customername;

-- Q6. Find the total revenue generated by each product category.
select category,
sum(quantity * unitprice) as total_revenue
from customers
inner join orders
on customers.customerid = orders.customerid
group by category
order by total_revenue desc;

-- Q7. Display each customer's latest order date.
select customername,
max(orderdate) as latest_order_date
from customers
inner join orders
on customers.customerid = orders.customerid
group by customername
order by latest_order_date desc;

-- Q8. Find the most ordered product. 
select productname,sum(quantity) as total_orders
from customers
inner join orders
on customers.customerid = orders.customerid
group by productname
order by total_orders desc
limit 1;

-- Q9. Display customer name, product name, category, payment method, and order status.
select customername,productname,category,paymentmethod,orderstatus 
from Customers
inner join Orders
on Customers.customerid = Orders.customerid;

-- Q10. Find the average rating of products purchased by customers from each country.
select country,avg(rating) as average_rating
from customers
inner join orders
on customers.customerid = orders.customerid
inner join products
on orders.productid = products.productid
group by country
order by average_rating desc;

       -- SUBQUERIES --
-- Q11. Find products priced above the average product price.    
select  productname,price from products
where price > ( select avg(price) from Products order by price desc);  

-- Q12. Find the highest-priced product in each category.
select productname,category,price
from products
where price =
(select max(price) from products as product_table
    where product_table.category = products.category);
    
-- Q13. Find customers who have placed at least one order.
select
customername
from customers
where customerid in
(select customerid from orders);

-- Q14. Find orders whose total amount is greater than the average order amount.
select orderid,customerid,productname,quantity,unitprice,
(quantity * unitprice) as total_amount
from orders
where (quantity * unitprice) >
(select avg(quantity * unitprice)from orders);

-- Q15. Display each product along with the average product price.
select productname,price,
(select avg(price) from products) as average_price
from products;

 --   COMMON TABLE EXPRESSIONS (CTE) --
 
-- Q16. Display the total revenue generated by each category.
with category_revenue as
(select category,
sum(quantity * unitprice) as total_revenue
from orders
group by category)
select *
from category_revenue;

-- Q17. Display the total number of orders placed by each customer.
with customer_orders as
(select customerid,count(orderid) as total_orders
from orders
group by customerid)
select *
from customer_orders;

-- Q18. Display the total quantity sold for each product.
with product_sales as
(select productid,
sum(quantity) as total_quantity
from orders
group by productid)
select *
from product_sales;

-- Q19. Find the average price of all products.
with average_price as
(select avg(price) as average_price
from products)
select *
from average_price;

-- Q20. Find the highest-priced product.
with highest_price as
(select max(price) as highest_price from products)
select *
from highest_price;

     -- WINDOW FUNCTIONS --
     
     
-- Q21. Assign a row number to every product based on price.
select productname,category,price,
row_number() over(order by price desc) as row_num
from products;

-- Q22. Rank products by price.
select productname,category,price,
rank() over(order by price desc) as product_rank
from products;

-- Q23 .Rank products by rating without skipping ranks.
select productname,category,price,
rank() over(order by price desc) as product_rank
from products;

-- Q24. Compare each order amount with the previous order.
select orderid,orderdate,
(quantity * unitprice) as order_amount,
lag(quantity * unitprice) over(order by orderdate) as previous_order_amount
from orders;

-- Q25. Compare each order amount with the next order.
select orderid,orderdate,
(quantity * unitprice) as order_amount,
lead(quantity * unitprice) over(order by orderdate) as next_order_amount
from orders;

           -- END --
